### ISSUE TITLE
push new content to rep (I have problems here)

### ISSUE THREAD

**Issue by alj1983** [CompBioSnippets/CompBioSnippets#3]

**Comment by gghill** [comment]
Large html files are difficult for GitHub to preview, but can still be uploaded. However, if the links in the README.org file are made to the raw version and prefixed with `https://htmlpreview.github.io/?` they link to fully loaded html version. This is the best way to facilitate access in my opinion. I have updated my content accordingly using [[LINK][DESCRIPTION]] syntax in the README file.
[read more here](https://leaherb.com/github-html-preview/)
